services:
  haskell:
    build: haskell
    volumes:
      - ./haskell:/haskell
    tty: true
  notebook:
    build:
      context: notebook
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebook/work:/home/jovyan/work
